config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/score', to: 'static_pages#score'
  get 'password_resets/new'
  get 'password_resets/edit'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/gyms_search',    to: 'gyms#search'
  post   '/gyms_search',    to: 'gyms#search'
  get    '/gyms_choose',    to: 'gyms#choose'
  post   '/gyms_choose',    to: 'gyms#choose'
  get    '/rankings', to: 'records#rank'
  get    '/graphs', to: 'records#graph'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :relationships,       only: %i[create destroy]
  resources :records,             only: %i[index new create destroy] do
    resources :likes, only: %i[create destroy]
  end
  resources :gyms, only: %i[index new create update destroy]
  get '/gyms/:id', to: 'gyms#edit', as: 'edit_gym'
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = object.errors.count
      | 個のエラーがあります 
    ul

    .text-danger
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_following_record.html.slim
- if @following_record_items.any?
  .content_center
    = will_paginate(@following_record_items, inner_window: 1, outer_window: 0)
  ol.records
    = render @following_record_items
  .content_center
    = will_paginate(@following_record_items, inner_window: 1, outer_window: 0)

app/views/shared/_index_stats.html.slim
- user ||= current_user
.stats.stats-index
  a.css-br href="#{following_user_path(user)}" 
    strong.stat id="following_#{user.id}"
      = user.following.count
    |  フォロー中
  a href="#{followers_user_path(user)}" 
    strong.stat id="followers_#{user.id}"
      = user.followers.count
    |  フォロワー 
  strong.stat id="score_#{user.id}"
    = point
  |  pt

app/views/shared/_new_gym_form.html.slim
= form_with(model: @gym, local: true) do |f|
  = f.label :name
  span.required
    | 必須
  = f.text_field :name, value: @gym_name, readonly: true, placeholder: "例）Nobolt 東京店", class: 'form-control'
  = f.hidden_field :prefecture_code, value: (JpPrefecture::Prefecture.find name: @gym_prefecture).code, class: 'form-control'
  = f.label :prefecture
  span.required
    | 必須
  = f.text_field :prefecture, value: @gym_prefecture, readonly: true, placeholder: "例）東京都", class: 'form-control'
  = f.label :address
  span.required
    | 必須
  = f.text_field :address, value: @gym_address, readonly: true, placeholder: "例）東京都新宿区新宿1-2-3", class: 'form-control'
  span.picture
    = f.label :picture
    = f.file_field :picture
  = f.label :url
  = f.text_field :url, placeholder: "例）https://nobolt.com", class: 'form-control'
  = f.label :business_hours
  = f.text_field :business_hours, placeholder: "例）9:00-22:00", class: 'form-control'
  = f.label :price
  = f.text_area :price, placeholder: "例）10:00-18:00 1800円", class: 'form-control'
  = f.submit "ジム登録", class: "btn btn-primary"

app/views/shared/_record_form.html.slim
= form_with(model: Record.new, local: true) do |f|
  .record-form
    = f.label :gym_name
    span.required
        | 必須
    = f.text_field :gym_name, value: @gym_name, readonly: true, placeholder: "例）Nobolt 東京店", class: 'form-control'
    p
      | 別のジムで記録する場合はこちら⇨
      = link_to "ジム選択", gyms_path, id: 'gym_select_link'
  .record-form
    = f.label :grade
    span.required
        | 必須
    = f.select :grade, Grade.pluck(:name), {},:class=> 'form-control'
  .record-form
    = f.label :challenge
    span.required
        | 必須
    = f.text_field :challenge, placeholder: "例）1番、スラブの四角、100°の棒など", class: 'form-control'
  .record-form
    = f.label :strong_point
    span.required
        | 必須
    .custom-control.custom-switch.first-clear
      = f.check_box :strong_point, class:"custom-control-input", id:"customSwitch1"
      = f.label :strong_point, "1度目のトライでクリアした場合にチェック", class:"custom-control-label", for:"customSwitch1"
  .record-form
    span.picture
      = f.label :picture
      = f.file_field :picture
  .record-form
    = f.submit "登録", class: "btn btn-primary"

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  a href="#{following_user_path(@user)}" 
    strong.stat id="following_#{@user.id}"
      = @user.following.count
    |  フォロー中
  a href="#{followers_user_path(@user)}" 
    strong.stat id="followers_#{@user.id}"
      = @user.followers.count
    |  フォロワー 
  strong.stat id="score_#{@user.id}"
    = @point
  |  pt

app/views/shared/_user_info.html.slim
.user_item
  = link_to image_tag(current_user.picture.url), current_user, class: "avater_home"
  .user_basic_info
    h1
      = current_user.name
    span
      = link_to "マイページ", current_user
    span
      | 投稿数 
      = current_user.records.count