config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/score', to: 'static_pages#score'
  get 'password_resets/new'
  get 'password_resets/edit'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/gyms_search',    to: 'gyms#search'
  post   '/gyms_search',    to: 'gyms#search'
  get    '/gyms_choose',    to: 'gyms#choose'
  post   '/gyms_choose',    to: 'gyms#choose'
  get    '/rankings', to: 'records#rank'
  get    '/graphs', to: 'records#graph'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :relationships,       only: %i[create destroy]
  resources :records,             only: %i[index new create destroy] do
    resources :likes, only: %i[create destroy]
  end
  resources :gyms, only: %i[index new create update destroy]
  get '/gyms/:id', to: 'gyms#edit', as: 'edit_gym'
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :gym
  belongs_to :grade
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  default_scope -> { order(created_at: :desc) }
  validates :grade_id, presence: true
  validates :strong_point, presence: true
  validates :challenge, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true
  validates :gym_id, presence: true
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, '画像は5MBが上限です') if picture.size > 5.megabytes
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: :destroy
  before_action :set_gym, only: %i[new search]

  def index
    @records = Record.includes(:grade, :gym, :user, :likes).paginate(page: params[:page])
  end

  def show
    @like = Like.new
  end

  def new
    @record = Record.new
    render 'new'
  end

  def create
    @record = current_user.records.build(record_params)
    if params[:record]['gym_name'].present?
      gym_name = Gym.find_by(name: params[:record]['gym_name'])
      @record.gym_id = gym_name.id
    end
    if params[:record]['grade'].present?
      grade = Grade.find_by(name: params[:record]['grade'])
      @record.grade_id = grade.id
    end
    flash.now[:info] = '記録を保存しました' if @record.save
    set_gym
    render 'new'
  end

  def destroy
    @record.destroy
    flash[:success] = '記録を削除しました'
    redirect_to request.referrer || root_url
  end

  def rank
    query = cal_query
    rank_value(query)
  end

  def graph
    cal_graph
  end

  private

  def record_params
    params.require(:record).permit(:challenge, :strong_point, :picture)
  end

  def graph_time(time_format)
    @graph_value = Record.joins(:grade)
                         .unscope(:order)
                         .select("(sum(grade_point) + sum(strong_point))*10 as score,
                                 date_format(records.created_at ,'#{time_format}') as date")
                         .where('records.user_id = ?', current_user.id)
                         .where('records.created_at between ? and ?', @from, @to)
                         .group('date')
                         .order('date')
  end

  def cal_graph
    @count = 0
    @chart_pre = true
    @chart_next = true
    @chart = []

    # 集計単位を判別
    @selected_term = if params[:term].present?
                       params[:term]
                     else
                       'day'
                     end

    # 集計の基準日を計算
    if params[:pre_preview].present?
      case @selected_term
      when 'month'
        @from_to = Date.parse(params[:pre_preview]) << 6
      when 'week'
        @from_to = Date.parse(params[:pre_preview]) - 7 * 8
      when 'day'
        @from_to = Date.parse(params[:pre_preview]) - 7
      end
    elsif params[:next_preview].present?
      case @selected_term
      when 'month'
        @from_to = Date.parse(params[:next_preview]) >> 6
      when 'week'
        @from_to = Date.parse(params[:next_preview]) + 7 * 8
      when 'day'
        @from_to = Date.parse(params[:next_preview]) + 7
      end
    else
      @from_to = if params[:from_to].present?
                   Date.parse(params[:from_to])
                 else
                   Time.current.to_date
                 end
    end

    # グラフの値を計算
    case @selected_term
    when 'month'
      @selected_term_jp = '月'
      if @from_to.strftime('%m').to_i < 7
        # 1/1~6/30
        @from = @from_to.beginning_of_year.to_date
        @to = @from.since(5.month).end_of_month.to_date
      else
        # 7/1~12/31
        @from = @from_to.end_of_year.ago(5.months).beginning_of_month.to_date
        @to = @from_to.end_of_year.to_date
      end

      graph_time('%Y/%m')

      6.times do |i|
        t = (@from >> i).strftime('%Y/%m')
        temp_score = 0
        @graph_value.each do |g|
          temp_score = g.score.to_i if t == g.date
        end
        @chart.append([t, temp_score])
      end
    when 'week'
      @selected_term_jp = '週'

      @from = @from_to.ago(7.weeks).beginning_of_week(:sunday).to_date
      @to = @from_to.end_of_week(:sunday).to_date

      graph_time('%Y/%U weeks')

      8.times do |i|
        t = (@from + i * 7)
        temp_score = 0
        @graph_value.each do |g|
          temp_score = g.score.to_i if (t + 1).strftime('%Y/%U weeks') == g.date
        end
        @chart.append([t.strftime('%Y/%m/%d週').to_s, temp_score])
      end
    when 'day'
      @selected_term_jp = '日'

      @from = @from_to.beginning_of_week(:sunday).to_date
      @to = @from_to.end_of_week(:sunday).to_date

      graph_time('%Y/%m/%d')

      7.times do |i|
        t = (@from + i).strftime('%Y/%m/%d')
        temp_score = 0
        @graph_value.each do |g|
          temp_score = g.score.to_i if t == g.date
        end
        @chart.append([t + "(#{%w[日 月 火 水 木 金 土][i]})", temp_score])
      end
    end

    # 前の日付が記録を始めた時期より前だったら、左矢印を非活性状態にする
    if Record.where(user_id: current_user.id).blank? \
       || @from <= Record.where(user_id: current_user.id).last.created_at.to_date
      @chart_pre = false
    end
    # 次の日付が未来だったら、右矢印を非活性状態にする
    @chart_next = false if @to >= Date.today

    @from = @from.strftime('%Y/%m/%d')
    @to = @to.strftime('%Y/%m/%d')
  end

  def set_gym
    if params[:selection_gym_name].present?
      @gym_name = params[:selection_gym_name]
    elsif Record.find_by(user_id: current_user.id).present?
      latest_record = Record.find_by(user_id: current_user.id)
      @gym_name = Gym.find(latest_record.gym_id).name
    else
      flash[:info] = 'まずは、ジムを選択してください'
      redirect_to gyms_path
    end
  end

  def cal_query
    all_term = '全期間'
    all_gym = '全てのジム'

    @month_choice = [all_term] + (Record.last[:created_at].to_date.beginning_of_month..Date.today)
                    .select { |date| date.day == 1 }.map { |item| item.strftime('%Y年%m月') }.reverse

    @gym_choice = [all_gym] + Gym.pluck('name')

    if params[:month].present?
      if params[:month] != all_term
        @begin_time = Date.strptime(params[:month], '%Y年%m月').beginning_of_month
        @end_time = Date.strptime(params[:month], '%Y年%m月').end_of_month
      else
        @begin_time = Record.last[:created_at].to_date.beginning_of_month
        @end_time = Date.today.end_of_month
      end
      @selected_month = params[:month]
    else
      @begin_time = Time.current.beginning_of_month
      @end_time = Time.current.end_of_month
      @selected_month = Time.current.strftime('%Y年%m月')
    end

    if params[:gym].present? && params[:gym] != all_gym
      @target_gym = Gym.find_by(name: params[:gym]).id
      @selected_gym = params[:gym]
    else
      @target_gym = Gym.pluck('id')
      @selected_gym = all_gym
    end

    ActiveRecord::Base.sanitize_sql_array(['
      select user_id,
             score,
             (select (COUNT(*) + 1)
             from (select r.user_id,
                           (sum(g.grade_point) + sum(r.strong_point)) * 10 as score
                   from records as r
                   inner join grades as g
                           on r.grade_id = g.id
                           where (r.gym_id in (:gym_ids)) and (r.created_at between :begin_times and :end_times)
                   group by r.user_id
                   order by score DESC) as s1
             where s2.score < s1.score) as rank_number
      from
      (select r.user_id,
              (sum(g.grade_point) + sum(r.strong_point)) * 10 as score
      from records as r
      inner join grades as g
              on r.grade_id = g.id
      where (r.gym_id in (:gym_ids)) and (r.created_at between :begin_times and :end_times)
      group by r.user_id
      order by score DESC) as s2;
      ', { gym_ids: @target_gym, begin_times: @begin_time, end_times: @end_time }])
  end

  def rank_value(query)
    @ranks = ActiveRecord::Base.connection.select_all(query)

    @my_rank = 0
    @ranks.each_with_index do |rank, _i|
      if rank['user_id'] == current_user.id
        @my_rank = rank['rank_number']
        break
      end
    end
    @total_user = @ranks.count
    @ranks = @ranks.to_a.paginate(page: params[:page], per_page: 100)
  end

  def correct_user
    @record = current_user.records.find_by(id: params[:id])
    redirect_to root_url if @record.nil?
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_record.html.slim
li.record id="record-#{record.id}"
  = link_to image_tag(record.user.picture.url), record.user, class: "avater"
  span.user
    = link_to record.user.name, record.user
    - if record.strong_point == "1"
      span.good-mark
        = "一撃"
  .content
    = record.gym.name
  span.content
    = record.grade.name
    span.content-challenge
      = record.challenge
    = image_tag record.picture.url if record.picture?
  span.timestamp
    = l record.created_at
    span.like-button id="likes_buttons_#{record.id}"
      = render partial: 'likes/like', locals: { record: record, likes: @likes}
    - if current_user?(record.user)
      = link_to "削除", record, method: :delete, data: { confirm: "本当に削除しますか?" }, class: "record-delete"

app/views/records/_show.html.slim
.text-center
    | 集計期間：#{@selected_month}
    .br
    |　ジム：#{@selected_gym}
    .br
    / もし期間中に自分の実績があれば、順位を表示する
    - if @my_rank == 0
       = 'あなたはこの期間、このジムで実績がありません'
    - else
      = "あなたの順位は #{@total_user}人中"
      strong
        = " #{@my_rank}位 "
      = "です"
.content_center.rank-paginate
  = will_paginate(@ranks, inner_window: 1, outer_window: 0)
table.table.table-hover.table-bordered
    thead.thead-light
      tr.text-center
        th = "順位"
        th = "ユーザー名"
        th = "スコア"
    tbody
      - @ranks.each_with_index do |rank,i|
        - user = User.find(rank["user_id"])
        tr
          td.rank-body id="rank-number-#{user.id}"
            / １位〜３位の場合は、順位に王冠を表示する
            .rank-text
              - if rank["rank_number"]!= 1 && rank["rank_number"] != 2 && rank["rank_number"] != 3
                = rank["rank_number"]
              - else
                image.crown src="/assets/crown-#{rank["rank_number"]}.png"
          td.text-left id="user-name-#{user.id}"
            = link_to(user_path(user)) do
              .avater-rank
                = image_tag(user.picture.url).to_s
                = user["name"]
          td.rank-body id="score-#{user.id}"
            .rank-text
              = rank["score"].to_i.to_s(:delimited)
              | pt
.content_center
  = will_paginate(@ranks, inner_window: 1, outer_window: 0)

app/views/records/_term_form.html.slim
= form_with(url: rankings_path, method: :get, local: true) do |f|
  .container
    .row.no-gutters.justify-content-center
      = f.select :month, @month_choice, {selected: @selected_month}, :class=> 'form-control col-10 col-sm-10 col-md-5'
      = f.select :gym, @gym_choice, {selected: @selected_gym}, :class=> 'form-control search-window col-10 col-sm-10 col-md-5'
      = f.submit "集計", class: "btn btn-primary col-10 col-sm-10  col-md-1"

app/views/records/graph.html.slim
- provide(:title, 'グラフ')
.container
  h3.text-center.page-title
    = "#{current_user.name}さんのグラフ（#{@selected_term_jp}別）"

  - @page_title = "#{@from}〜#{@to}"

  ul.nav.nav-tabs.mx-auto.justify-content-around.form-inline
    li.nav-item
      = link_to "日", graphs_path(term: "day",from_to: @from_to ), class: "nav-link", id: "day"
    li.nav-item
      = link_to "週", graphs_path(term: "week",from_to: @from_to ), class: "nav-link", id: "week"
    li.nav-item
      = link_to "月", graphs_path(term: "month",from_to: @from_to ), class: "nav-link", id: "month"

  input#term type="hidden" value=@selected_term

  .col-md-6.mx-auto
    .form-inline.mb-3.justify-content-around
      - if @chart_pre
        = link_to "", graphs_path(pre_preview: @from_to, term: @selected_term), class: "fa fa-chevron-left mr-3"
      - else
        div.fa.fa-chevron-left.mr-3.gray
      span.ml-2.mr-2.lead
        strong
          = @page_title
      - if @chart_next
        = link_to "", graphs_path(next_preview: @from_to, term: @selected_term), class: "fa fa-chevron-right ml-3"
      - else
        div.fa.fa-chevron-right.ml-3.gray

  = column_chart @chart, ytitle: "スコア"

app/views/records/index.html.slim
- provide(:title, '完登記録(全ユーザ)')
.container
  h2.text-center.page-title
    | 完登記録(全ユーザ)

  .col-10.col-sm-10.col-md-8.col-lg-6.col-xl-5.mx-auto
    - if @records.any?
      .content_center
        = will_paginate(@records, inner_window: 1, outer_window: 0)
      ol.records
        = render @records
      .content_center
        = will_paginate(@records, inner_window: 1, outer_window: 0)

app/views/records/new.html.slim
- provide(:title, '記録する')
.row.no-gutters
  .col-10.col-sm-8.col-md-8.col-lg-6.col-xl-5.mx-auto.center
    h2.page-title
      | 記録する
    = render 'shared/error_messages', object: @record
    #shared_record_form
      = render 'shared/record_form'

app/views/records/rank.html.slim
- provide(:title, 'ランキング')
.container
  .row.no-gutters.content_center
    .col-sd-6
      h2.page-title
        | ランキング

  = render 'term_form'

  #rank-show
    = render 'show'