config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/score', to: 'static_pages#score'
  get 'password_resets/new'
  get 'password_resets/edit'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/gyms_search',    to: 'gyms#search'
  post   '/gyms_search',    to: 'gyms#search'
  get    '/gyms_choose',    to: 'gyms#choose'
  post   '/gyms_choose',    to: 'gyms#choose'
  get    '/rankings', to: 'records#rank'
  get    '/graphs', to: 'records#graph'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :relationships,       only: %i[create destroy]
  resources :records,             only: %i[index new create destroy] do
    resources :likes, only: %i[create destroy]
  end
  resources :gyms, only: %i[index new create update destroy]
  get '/gyms/:id', to: 'gyms#edit', as: 'edit_gym'
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :records, dependent: :destroy
  has_many :users, through: :records
  validates :name, presence: true, uniqueness: true
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  validates :url, format: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/, allow_blank: true
  validate :business_hours
  validates :address, presence: true
  validate :price
  validates :prefecture_code, presence: true

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, '画像は5MBが上限です') if picture.size > 5.megabytes
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: :destroy
  def index
    @q = Gym.ransack(params[:q])
    @gyms = @q.result.page(params[:page]).order('name ASC')
  end

  def new
    @gym = Gym.new
  end

  def search
    if params[:search].present?
      @keyword = params[:search]
      @client = GooglePlaces::Client.new(ENV['GOOGLE_API_KEY'])
      @gyms = @client.spots_by_query("#{@keyword}ボルダリング", language: 'ja', region: 'ja')
    end

    @gym = Gym.new
    render 'new'
  end

  def choose
    if params[:gym_name] && params[:gym_address]
      @gym_name = params[:gym_name]
      @gym_address = params[:gym_address]
      regions = region_array
      regions.each do |region|
        @gym_prefecture = params[:gym_address][region]
        break if @gym_prefecture == region
      end
    end

    @gym = Gym.new
    render 'new'
  end

  def create
    @gym = Gym.new(gym_params)
    if @gym.save
      flash.now[:info] = "#{@gym.name} を保存しました"
      @gym_name = @gym.name
      @record = Record.new
      render('records/new')
    else
      gym_info
      render 'new'
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])
    flash.now[:success] = 'ジムの編集に成功しました' if @gym.update_attributes(gym_params)
    render 'edit'
  end

  def destroy
    @gym.destroy
    flash[:success] = 'ジムを削除しました'
    redirect_to gyms_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gym
    @gym = Gym.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gym_params
    params.require(:gym).permit(:name, :prefecture_code, :address, :picture, :url, :business_hours, :price)
  end

  def gym_info
    @gym_name = params[:gym][:name]
    @gym_address = params[:gym][:address]
    @gym_prefecture = (JpPrefecture::Prefecture.find params[:gym][:prefecture_code]).name
  end

  def region_array
    %w[北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県 \
       茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県 \
       新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 \
       静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 \
       奈良県 和歌山県 鳥取県 島根県 岡山県 広島県 山口県 \
       徳島県 香川県 愛媛県 高知県 福岡県 佐賀県 長崎県 \
       熊本県 大分県 宮崎県 鹿児島県 沖縄県]
  end

  # 管理者かどうか確認
  def admin_user
    @gym = Gym.find(params[:id])
    redirect_to(gyms_url) unless current_user.admin?
  end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_gym.html.slim
.gym_list
  = link_to controller: 'records', action: 'new', selection_gym_name: gym.name do
    .gym-card
      .gym-image
        - if gym.picture?
          = image_tag gym.picture.url
        - else
          = image_tag "/assets/bouldering_wall#{[1, 2, 3, 4, 5].sample.to_s}"
      ul.gym-card-content
        li.gym-card-name
          = gym.name
        li
          = "県名：" + (JpPrefecture::Prefecture.find gym.prefecture_code).name
        li
          = "URL：" + gym.url if gym.url
        li
          = "時間：" + gym.business_hours if gym.business_hours
        li
          = "料金：" + gym.price if gym.price
        li.gym-card-edit
          = link_to "編集", edit_gym_path(gym)
          .gym-card-delete
            - if current_user.admin?
              = link_to "削除", gym, method: :delete, data: { confirm: "本当に削除しますか?" }

app/views/gyms/_select.html.slim
= search_form_for @q do |f|
  .row.no-gutters.justify-content-center
    = f.search_field :name_or_address_cont, placeholder: "地名・キーワードで検索", class: 'form-control col-10 col-sm-10 col-md-5 search-box'
    = f.collection_select :prefecture_code_eq, JpPrefecture::Prefecture.all,
      :code, :name, {include_blank: '都道府県から探す'}, :class=>'form-control search-window col-10 col-sm-10 col-md-5 search-box'
    = f.submit "検索", class: "btn btn-primary col-10 col-sm-10  col-md-1 search-box"

app/views/gyms/edit.html.slim
- provide(:title, 'ジム編集')
.row.no-gutters
  .col-10.col-sm-8.col-md-8.col-lg-6.col-xl-5.mx-auto.center
    h1
      | ジム編集
    = form_with(model: @gym, local: true) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :name
      span.required
        | 必須
      = f.text_field :name, readonly: true, class: 'form-control'
      = f.hidden_field :prefecture_code, value: @gym.prefecture_code, class: 'form-control'
      = f.label :prefecture
      span.required
        | 必須
      = f.text_field :prefecture, value: (JpPrefecture::Prefecture.find @gym.prefecture_code).name, readonly: true, class: 'form-control'
      = f.label :address
      span.required
        | 必須
      = f.text_field :address, value: @gym.address, readonly: true, class: 'form-control'
      span.picture
        = f.label :picture
        = f.file_field :picture
      = f.label :url
      = f.text_field :url, class: 'form-control'
      = f.label :business_hours
      = f.text_field :business_hours, class: 'form-control'
      = f.label :price
      = f.text_area :price, class: 'form-control'
      = f.submit "更新", class: "btn btn-primary"
    = link_to controller: 'records', action: 'new', selection_gym_name: @gym.name do
      | このジムで記録する

app/views/gyms/index.html.slim
- provide(:title, 'ジム選択')
.container
  h2.text-center.page-title
    | ジム選択
  = render 'select'
  p.text-center
    | 新しくジムを登録する場合はこちら⇨
    = link_to "新規ジム登録", new_gym_path
  ul.gym_list_box.content_center
    = render @gyms
  .content_center
    = will_paginate(@gyms, inner_window: 1, outer_window: 0)

app/views/gyms/new.html.slim
- provide(:title, '新規ジム登録')
.row.no-gutters
  .col-10.col-sm-8.col-md-8.col-lg-6.col-xl-5.mx-auto.center
    h1
      | 新規ジム登録
    = render 'shared/error_messages', object: @gym
    - if !@gym_name
      = form_with(url: gyms_search_path, method: :post, local: true) do |search_f|
        = search_f.label :search, 'ジム検索'
        = search_f.text_field :search, value: @keyword, placeholder: "例）Nobolt", class: "form-control"
        = search_f.submit '検索'
      - if @gyms
        table
          thead
            tr
              th
                | ジム名
              th
                | 住所
              th[colspan="1"]
          tbody
            - @gyms.each do |gym_search|
              tr
                td
                  = gym_search["name"]
                td
                  = gym_search["formatted_address"]
                td
                  = button_to "選択", {controller: 'gyms', action: 'choose'}, {method: :post, params: {gym_name: gym_search["name"], gym_address: gym_search["formatted_address"]}}
    - else
      = render 'shared/new_gym_form'
      p
        | 別のジムを登録する場合はこちら⇨
        = link_to "新規ジム登録", new_gym_path
    p
      | 記録するページに戻りたい場合はこちら⇨
      = link_to "記録する", new_record_path