config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/score', to: 'static_pages#score'
  get 'password_resets/new'
  get 'password_resets/edit'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/gyms_search',    to: 'gyms#search'
  post   '/gyms_search',    to: 'gyms#search'
  get    '/gyms_choose',    to: 'gyms#choose'
  post   '/gyms_choose',    to: 'gyms#choose'
  get    '/rankings', to: 'records#rank'
  get    '/graphs', to: 'records#graph'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :relationships,       only: %i[create destroy]
  resources :records,             only: %i[index new create destroy] do
    resources :likes, only: %i[create destroy]
  end
  resources :gyms, only: %i[index new create update destroy]
  get '/gyms/:id', to: 'gyms#edit', as: 'edit_gym'
end

app/views/layouts/_footer.html.slim
footer
  .container
    .text-center.footer-menu
      = link_to "スコアとは？", score_path
      br © 2021 Nobolt All rights reserved.

app/views/layouts/_header.html.slim
header.container-fluid#header
  nav.navbar.navbar-expand-md.navbar-dark.bg-primary
    .container.sp-header-container
      = link_to "Nobolt", root_path, id: "logo", class: "navbar-brand header-logo"
      #navbarColor02.navbar-collapse.collapse[style=""]
        ul.navbar-nav.ml-auto.pc-nav
          = render 'layouts/header_pc_nav'
      nav.sp-nav
        ul
          = render 'layouts/header_sp_nav'
      #hamburger
        span

app/views/layouts/_header_pc_nav.html.slim
- if logged_in?
  li.nav-item
    = link_to "グラフ", graphs_path, class: "nav-link"
  li.nav-item
    = link_to "ランキング", rankings_path, class: "nav-link"
  li.nav-item
    = link_to "記録する", new_record_path, class: "nav-link"
  li.nav-item.dropdown
    a.nav-link.dropdown-toggle[data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"]
      | 完登記録
    .dropdown-menu[x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 40px, 0px);"]
      = link_to "マイページ", current_user, class: "dropdown-item"
      = link_to "フォロー中", root_path, class: "dropdown-item"
      = link_to "全ユーザ", records_path, class: "dropdown-item"
  li.nav-item.dropdown#pc-dropdown
    a.nav-link.dropdown-toggle[data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"]
      | アカウント
    .dropdown-menu[x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 40px, 0px);"]
      = link_to "プロフィール編集", edit_user_path(current_user), class: "dropdown-item"
      = link_to "ユーザ一覧", users_path, class: "dropdown-item"
      .dropdown-divider
      = link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item"
- else
  li.nav-item
    = link_to "ログイン", login_path, class: "nav-link"
  li.nav-item
    = link_to "新規登録", signup_path, class: "nav-link"

app/views/layouts/_header_sp_nav.html.slim
- if logged_in?
  li.nav-item
    = link_to "グラフ", graphs_path, class: "nav-link"
  li.nav-item
    = link_to "ランキング", rankings_path, class: "nav-link"
  li.nav-item
    = link_to "記録する", new_record_path, class: "nav-link"
  li.nav-item.dropdown
    a.nav-link.dropdown-toggle[data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"]
      | 完登記録
    .dropdown-menu[x-placement="bottom-start"]
      = link_to "マイページ", current_user, class: "dropdown-item"
      = link_to "フォロー中", root_path, class: "dropdown-item"
      = link_to "全ユーザ", records_path, class: "dropdown-item"
  li.nav-item.dropdown
    a.nav-link.dropdown-toggle[data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"]
      | アカウント
    .dropdown-menu[x-placement="bottom-start"]
      = link_to "プロフィール編集", edit_user_path(current_user), class: "dropdown-item"
      = link_to "ユーザ一覧", users_path, class: "dropdown-item"
      .dropdown-divider
      = link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item"
  li.nav-item.close
    span
      |  閉じる
- else
  li.nav-item
    = link_to "ログイン", login_path, class: "nav-link"
  li.nav-item
    = link_to "新規登録", signup_path, class: "nav-link"
  li.nav-item.close
    span
      |  閉じる

app/views/layouts/application.html.slim
html
  head
    title
      = full_title(yield(:title))
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="description" content=""
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container-fluid#content
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "flash_message alert alert-#{message_type}")
      = yield
    = render 'layouts/footer'
    .container
      = debug(params) if Rails.env.development?